/**
 * ContextEngine — Orchestrates memory layers for Claudia
 *
 * Manages ZepLoop (and later MemoryStore), handles toggle state,
 * and assembles the context blocks injected into conversations.
 *
 * Integration point: the SDK bridge calls these hooks at the right
 * moments in the message lifecycle.
 */

// Import from the esbuild bundle (has @getzep/zep-cloud inlined).
// Generated by `npm run bundle:bridge` — runs before both dev and build.
import { ZepLoop } from "./zep-loop.bundle.mjs";

const CONTEXT_TIMEOUT_MS = 800; // Skip context rather than block longer than this

export class ContextEngine {
  /**
   * @param {object} config
   * @param {object} [config.zep] - Zep config: { apiKey, userId, defaultTemplate }
   * @param {boolean} [config.defaultActive=true] - Default toggle state for new conversations
   */
  constructor(config = {}) {
    this.zepLoop = null;
    this.active = config.defaultActive !== false;
    this._lastContext = null;
    this._sessionStartPromise = null; // Tracks in-flight session start
    this._turnCount = 0; // Track turns to strip user summary after first

    // Initialize Zep if configured
    if (config.zep?.apiKey) {
      this.zepLoop = new ZepLoop({
        apiKey: config.zep.apiKey,
        userId: config.zep.userId || "jason",
        defaultTemplate: config.zep.defaultTemplate || "general",
      });
    }
  }

  /** Toggle the pipeline on/off. Only affects Zep per-turn ingestion. */
  setActive(active) {
    this.active = active;
  }

  /** @returns {boolean} Current toggle state */
  isActive() {
    return this.active;
  }

  /**
   * Called when a new conversation session starts.
   * Initializes Zep thread. Fire-and-forget — first turn awaits if needed.
   *
   * @param {string} sessionId - Claude session ID
   * @param {string} [sessionType="general"] - "general", "book-work", "coaching"
   */
  async onSessionStart(sessionId, sessionType = "general") {
    if (!this.active || !this.zepLoop) return null;

    this._turnCount = 0;
    this._sessionStartPromise = this.zepLoop.start(sessionId, sessionType)
      .catch((err) => {
        console.error("[ContextEngine] Session start failed:", err.message);
      });

    return null;
  }

  /**
   * Called before a user message is sent to Claude.
   * Ingests the message to Zep and retrieves context in a single API call.
   * ~300ms blocking — Zep sees the message and selects relevant facts.
   *
   * @param {string} message - User message text
   * @returns {Promise<string|null>} Context block to prepend to user message
   */
  async onUserMessage(message) {
    if (!this.active || !this.zepLoop) {
      return null;
    }

    // If session start is still in flight, wait for it (only affects turn 1)
    if (this._sessionStartPromise) {
      await this._sessionStartPromise;
      this._sessionStartPromise = null;
    }

    // Single API call: ingest message + get context shaped by it.
    // Timeout: send without context rather than block the conversation.
    try {
      const ctx = await Promise.race([
        this.zepLoop.ingestAndRetrieve(message),
        new Promise((_, reject) =>
          setTimeout(() => reject(new Error("timeout")), CONTEXT_TIMEOUT_MS)
        ),
      ]);
      this._lastContext = ctx;
      this._turnCount++;
      return this._formatContextBlock(ctx);
    } catch (err) {
      if (err.message === "timeout") {
        console.error(`[ContextEngine] Context retrieval timed out (${CONTEXT_TIMEOUT_MS}ms), sending without context`);
        return null;
      }
      throw err;
    }
  }

  /**
   * Called after Claude responds. Fire-and-forget — don't block the UI.
   * Ingests assistant message for conversation continuity.
   *
   * @param {string} message - Assistant response text
   */
  onAssistantMessage(message) {
    if (!this.active || !this.zepLoop) return;

    this.zepLoop.ingestAssistant(message).catch((err) => {
      console.error("[ContextEngine] Failed to ingest assistant message:", err.message);
    });
  }

  /**
   * Format the raw context into the XML block for injection.
   * After the first turn, strips the USER_SUMMARY section to save tokens —
   * the summary is mostly static and only needs to be seen once per session.
   * @private
   */
  _formatContextBlock(zepContext) {
    if (!zepContext) return null;

    let context = zepContext;

    // After turn 1, strip the user summary (it's static and wastes tokens)
    if (this._turnCount > 1) {
      context = context.replace(
        /# This is the user summary\n<USER_SUMMARY>[\s\S]*?<\/USER_SUMMARY>\n*/,
        ""
      );
    }

    // If stripping left nothing meaningful, skip injection entirely
    const stripped = context.replace(/<\/?[A-Z_]+>/g, "").trim();
    if (!stripped) return null;

    return `<long_term_memory>\n${context}\n</long_term_memory>`;
  }

  /** Get the last retrieved context (for preview panel) */
  getLastContext() {
    return this._lastContext;
  }

  /** Session stats for /memory-status */
  getStats() {
    return {
      active: this.active,
      zep: this.zepLoop ? this.zepLoop.getStats() : null,
    };
  }
}
